apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealos-system

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: sealos-state-metric
  app.kubernetes.io/component: monitoring

images:
  - name: sealos-state-metric
    newName: ghcr.io/zijiren233/sealos-state-metric
    newTag: latest
